version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: appointment-db
    environment:
      POSTGRES_DB: clg-appointment
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:
